import {StyleSheet} from 'react-native';
import {theme} from '../services/Common/theme';
import {fontFamilies} from '../utils/fontFamilies';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    marginTop: '3%',
    paddingHorizontal: 16,
  },
  upperContainer: {
    borderRadius: 15,
    backgroundColor: theme.APP_COLOR_2,
  },
  userTile: {
    marginVertical: 22,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  userTitle: {
    fontSize: 16,
    lineHeight: 36,
    textAlign: 'center',
    fontFamily: fontFamilies.DefaultBold,
    color: theme.COLORS.WHITE,
  },
  upperContainerDivider: {
    height: 4,
    backgroundColor: theme.APP_COLOR_1,
  },
  verificationTile: {
    marginVertical: 22,
    marginHorizontal: 18,
  },
  verificationCount: {
    fontSize: 36,
    lineHeight: 41,
    textAlign: 'center',
    fontFamily: fontFamilies.DefaultBold,
    color: theme.COLORS.WHITE,
  },
  rowCenterBetween: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  verificationIcon: {
    height: 25,
    width: 25,
  },
  myVerifications: {
    fontSize: 15,
    marginTop: 15,
    lineHeight: 17,
    textAlign: 'right',
    fontFamily: fontFamilies.DefaultBold,
    color: theme.COLORS.WHITE,
  },
  successRateTile: {
    marginVertical: 22,
    marginHorizontal: 18,
  },
  successRateTileInner: {
    marginTop: 16,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  successRatePercentage: {
    fontSize: 36,
    lineHeight: 41,
    fontFamily: fontFamilies.DefaultBold,
    color: theme.COLORS.WHITE,
  },
  successRate: {
    fontSize: 15,
    marginTop: 15,
    lineHeight: 17,
    fontFamily: fontFamilies.DefaultBold,
    color: theme.COLORS.WHITE,
  },
  listContainer: {
    paddingBottom: '3%',
  },
  menuContainer: {
    marginTop: 17,
  },
  listItem: {
    marginVertical: 8,
  },
  listItemButton: {
    elevation: 5,
    borderRadius: 15,
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    paddingVertical: 18,
    paddingHorizontal: 26,
    shadowColor: '#000',
    flexDirection: 'row',
    shadowOffset: {width: 0, height: 4},
    backgroundColor: theme.APP_COLOR_2,
  },
  iconContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 48,
  },
  textContainer: {},
  titleContainer: {
    flex: 1,
    paddingHorizontal: 30,
  },
  titleText: {
    fontSize: 18,
    lineHeight: 21,
    fontFamily: fontFamilies.DefaultBold,
    textTransform: 'uppercase',
    color: theme.COLORS.WHITE,
  },
  subTitleText: {
    fontSize: 11,
    fontWeight: '300',
    marginTop: 5,
    lineHeight: 14,
    fontFamily: fontFamilies.Default,
    color: theme.COLORS.WHITE,
  },
  icons: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    margin: 6,
    marginRight: 10,
  },
  buttonCancel: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    margin: 6,
    marginLeft: 10,
    backgroundColor: 'red',
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  input: {
    borderWidth: 2,
    borderColor: 'gray',
    width: 165,
    height: 40,
    borderRadius: 7,
    padding: 0,
    marginTop: 11,
    lineHeight: 15.1,
    fontFamily: fontFamilies.DefaultLight,
    color: theme.COLORS.BLACK,
    textAlign: 'center',
  },
  inputDivider: {
    height: 1,
    marginVertical: 18,
    backgroundColor: theme.COLORS.TULIP_TREE,
  },
  inputLabel: {
    fontSize: 12,
    lineHeight: 11.5,
    fontFamily: fontFamilies.DefaultBold,
    textTransform: 'uppercase',
    color: theme.COLORS.BLACK,
  },
  buttonsRow: {
    flexDirection: 'row',
  },
  statContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  statBlock: {
    width: '100%',
    borderRadius: 20,
    padding: 16,
    backgroundColor: theme.APP_COLOR_2,
  },
  statTitleBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  statTitle: {
    marginLeft: 8,
    fontFamily: fontFamilies.Default,
    fontSize: 12,
    lineHeight: 20,
    color: theme.COLORS.WHITE,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  statValueBlock: {
    flexDirection: 'row',
  },
  statValue: {
    fontFamily: fontFamilies.Default,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '700',
    color: theme.COLORS.WHITE,
  },
  statSubValue: {
    fontFamily: fontFamilies.Default,
    fontSize: 16,
    lineHeight: 24,
    fontWeight: '300',
    color: theme.COLORS.WHITE,
  },
  statRank: {
    fontFamily: 'Poppins',
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '400',
    color: theme.COLORS.TULIP_TREE,
  },
});
