source 'https://github.com/CocoaPods/Specs.git'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

project './CleanApp.xcodeproj'
platform :ios, '13.0'

install! 'cocoapods', :deterministic_uuids => false

$RNMapboxMapsImpl = 'mapbox'

target 'CleanApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'react-native-charts-wrapper', :path => '../node_modules/react-native-charts-wrapper' # do not delete this 
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  target 'CleanAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  post_install do |installer|
   $RNMapboxMaps.post_install(installer)

   react_native_post_install(installer)

   installer.pods_project.build_configurations.each do |config|
     config.build_settings["CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES"] = true
   end

   installer.pods_project.targets.each do |target|
     target.build_configurations.each do |config|
       config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
       config.build_settings['HEADER_SEARCH_PATHS'] << '"${PODS_ROOT}/../../node_modules/react-native/ReactCommon" '
     end
   end

    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
      end
    end
  end
end
