export const initialState = {
  user: {
    type: 1,
    name: 'Jon Abbas Kok',
    gender: 0,
    location: 'Paris',
    cnic: '12345-1234567-1',
    phoneNumber: '3331234567',
  },
  authInfo: {refresh_token: '', access_token: ''},
  progressSettings: {show: false, promise: null},
  alertSettings: {settings: {}, promise: null},
  showVideoCallModal: true,
  appointmentBooked: false,
  newMessage: null,
  isTOCApproved: false,
  selectedLanguage: 'en',
  dataUsageSettings: false,
  verifySettings: false,
  walkthroughCurrentStep: 0,
  showLandingPageWalkthrough: false,
  showUploadImagePageWalkthrough: false,
  showVerifyImagePageWalkthrough: false,
  showAnnotateImagePageWalkthrough: false,
  currencySettings: {
    rate: 1,
    currency: 'USD',
  },
  overall: '',
  cameraAction: {
    requestCameraShot: false,
  },
  userLocation: {
    longitude: 0,
    latitude: 0,
    location: '',
    city: '',
  },
  cacheVault: {
    reports: 0,
    referrals: 0,
    offchainReports: 0,
    offchainReferrals: 0,
    onchainReports: 0,
    onchainReferrals: 0,
    onchainTotal: 0,
    offchainTotal: 0,
    total: 0,
  },
  mapLocation: {
    zoomLevel: 17,
    coordinates: [0, 0],
  },
  players: [],
  guilds: [],
  reports: [],
  fabShow: false,
};
